# Generated by Django 3.1 on 2020-08-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
