# Generated by Django 3.1 on 2020-08-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0002_auto_20200807_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
