# Generated by Django 3.1 on 2020-08-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0004_auto_20200810_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Hi, my name is <django.db.models.query_utils.DeferredAttribute object at 0x7fbfc3fbbe10>', max_length=500),
        ),
    ]
