# Generated by Django 3.1 on 2020-08-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0006_auto_20200813_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Hello, I am new here!', max_length=500),
        ),
    ]
