# Generated by Django 3.1 on 2020-11-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0008_auto_20200813_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Hello, follow and like!', max_length=500),
        ),
    ]
