# Generated by Django 3.1 on 2020-11-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0009_auto_20201126_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='reg.jpg', upload_to='avatars/'),
        ),
    ]
