# Generated by Django 3.1 on 2020-11-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_insta', '0010_auto_20201126_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
